runtime: python
env: flex
entrypoint: streamlit run main.py --server.port $PORT --server.address 0.0.0.0
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.13"
network:
  session_affinity: true